project:
  type: default

title: "Example — IDV Presentation Template"

requires:
  - IDV-Share/quarto-presentation-templates

extensions:
  - IDV-Share/quarto-presentation-templates

format:
  pptx:
    slide-level: 2

execute:
  freeze: auto